In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/raw/Table_03_All_Services.csv")

In [3]:
df.head()

,rundate,reporting_period,type_of_operations,airline_name,aircraft_km_x1000,no_flights,aircraft_hours,total_passengers_uplifted,seat_km_available_x1000,seat_km_used_x1000,cargo_tonnes_uplifted,total_tonne_km_available_x1000,tot_mail_tonne_km_used_x1000,total_freight_tonne_km_used_x1000,total_passenger_tonne_km_used_x1000
0,2/25/2026 9:40:39 AM,202512,Passenger,2 EXCEL AVIATION LTD T/A THE BLADES BROADSWORD...,10,21,18,1099,608,547,0,100,0,0,55
1,2/25/2026 9:40:39 AM,202512,Passenger,ACROPOLIS AVIATION LTD,49,10,62,89,928,444,0,171,0,0,37
2,2/25/2026 9:40:39 AM,202512,Passenger,AER LINGUS (UK) LTD,499,80,610,20005,157296,123243,152,23621,48,813,11587
3,2/25/2026 9:40:39 AM,202512,Passenger,AIRTANKER SERVICES LTD,230,39,301,3341,71197,36056,0,9381,0,0,3234
4,2/25/2026 9:40:39 AM,202512,Passenger,ASCEND AIRWAYS LTD,808,374,1300,4537,152653,121057,0,16486,0,0,10250

In [4]:
df.shape

(40, 15)

In [5]:
df.columns

Index(['rundate', 'reporting_period', 'type_of_operations', 'airline_name',
       'aircraft_km_x1000', 'no_flights', 'aircraft_hours',
       'total_passengers_uplifted', 'seat_km_available_x1000',
       'seat_km_used_x1000', 'cargo_tonnes_uplifted',
       'total_tonne_km_available_x1000', 'tot_mail_tonne_km_used_x1000',
       'total_freight_tonne_km_used_x1000',
       'total_passenger_tonne_km_used_x1000'],
      dtype='str')

In [6]:
df.dtypes

rundate                                  str
reporting_period                       int64
type_of_operations                       str
airline_name                             str
aircraft_km_x1000                      int64
no_flights                             int64
aircraft_hours                         int64
total_passengers_uplifted              int64
seat_km_available_x1000                int64
seat_km_used_x1000                     int64
cargo_tonnes_uplifted                  int64
total_tonne_km_available_x1000         int64
tot_mail_tonne_km_used_x1000           int64
total_freight_tonne_km_used_x1000      int64
total_passenger_tonne_km_used_x1000    int64
dtype: object

In [7]:
df.isna().sum()

rundate                                0
reporting_period                       0
type_of_operations                     0
airline_name                           0
aircraft_km_x1000                      0
no_flights                             0
aircraft_hours                         0
total_passengers_uplifted              0
seat_km_available_x1000                0
seat_km_used_x1000                     0
cargo_tonnes_uplifted                  0
total_tonne_km_available_x1000         0
tot_mail_tonne_km_used_x1000           0
total_freight_tonne_km_used_x1000      0
total_passenger_tonne_km_used_x1000    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df[df["airline_name"] == "BA CITYFLYER LTD"]

,rundate,reporting_period,type_of_operations,airline_name,aircraft_km_x1000,no_flights,aircraft_hours,total_passengers_uplifted,seat_km_available_x1000,seat_km_used_x1000,cargo_tonnes_uplifted,total_tonne_km_available_x1000,tot_mail_tonne_km_used_x1000,total_freight_tonne_km_used_x1000,total_passenger_tonne_km_used_x1000
6,2/25/2026 9:40:39 AM,202512,Passenger,BA CITYFLYER LTD,1562,2305,3437,183013,165584,125290,0,16558,0,0,11141

In [10]:
cityflyer = df[df["airline_name"] == "BA CITYFLYER LTD"].copy()

In [11]:
cityflyer

,rundate,reporting_period,type_of_operations,airline_name,aircraft_km_x1000,no_flights,aircraft_hours,total_passengers_uplifted,seat_km_available_x1000,seat_km_used_x1000,cargo_tonnes_uplifted,total_tonne_km_available_x1000,tot_mail_tonne_km_used_x1000,total_freight_tonne_km_used_x1000,total_passenger_tonne_km_used_x1000
6,2/25/2026 9:40:39 AM,202512,Passenger,BA CITYFLYER LTD,1562,2305,3437,183013,165584,125290,0,16558,0,0,11141

In [12]:
cityflyer["load_factor_pct"] = (
    cityflyer["seat_km_used_x1000"]
    / cityflyer["seat_km_available_x1000"]
    * 100
)

In [13]:
cityflyer[["airline_name", "reporting_period", "load_factor_pct"]]

       airline_name  reporting_period  load_factor_pct
6  BA CITYFLYER LTD            202512        75.665523

In [14]:
cityflyer["load_factor_pct"] = cityflyer["load_factor_pct"].round(2)

In [15]:
cityflyer[["airline_name", "reporting_period", "load_factor_pct"]]

       airline_name  reporting_period  load_factor_pct
6  BA CITYFLYER LTD            202512            75.67

In [16]:
cityflyer["passengers_per_flight"] = (
    cityflyer["total_passengers_uplifted"]
    / cityflyer["no_flights"]
).round(2)

In [17]:
cityflyer[
    [
        "airline_name",
        "reporting_period",
        "load_factor_pct",
        "passengers_per_flight"
    ]
]

       airline_name  reporting_period  load_factor_pct  passengers_per_flight
6  BA CITYFLYER LTD            202512            75.67                   79.4

In [18]:
cityflyer["avg_flight_distance_km"] = (
    cityflyer["aircraft_km_x1000"] * 1000
    / cityflyer["no_flights"]
).round(2)

In [19]:
cityflyer[
    [
        "airline_name",
        "reporting_period",
        "load_factor_pct",
        "passengers_per_flight",
        "avg_flight_distance_km"
    ]
]

,airline_name,reporting_period,load_factor_pct,passengers_per_flight,avg_flight_distance_km
6,BA CITYFLYER LTD,202512,75.67,79.4,677.66

In [20]:
url = "https://www.caa.co.uk/Documents/Download/26869/7bccbe92-007a-455b-a7ae-c206f9b1676d/4840"

url

'https://www.caa.co.uk/Documents/Download/26869/7bccbe92-007a-455b-a7ae-c206f9b1676d/4840'

In [21]:
import requests

response = requests.get(url)

response.status_code

200

In [22]:
response.headers.get("Content-Type")

'application/pdf'

In [23]:
csv_url = "https://www.caa.co.uk/Documents/Download/26869/7bccbe92-007a-455b-a7ae-c206f9b1676d/4838"

In [24]:
response = requests.get(csv_url)

response.headers.get("Content-Type")

'text/csv'

In [25]:
july_2026 = pd.read_csv(csv_url)

In [26]:
july_2026.shape

(32, 15)

In [27]:
july_2026[
    july_2026["airline_name"].str.contains("CITYFLYER", case=False, na=False)
]

,rundate,reporting_period,type_of_operations,airline_name,aircraft_km_x1000,no_flights,aircraft_hours,total_passengers_uplifted,seat_km_available_x1000,seat_km_used_x1000,cargo_tonnes_uplifted,total_tonne_km_available_x1000,tot_mail_tonne_km_used_x1000,total_freight_tonne_km_used_x1000,total_passenger_tonne_km_used_x1000
4,9/23/2026 7:59:15 AM,202607,Passenger,BA CITYFLYER LTD,2622,2859,5115,253173,277917,231880,0,27788,0,0,21090

In [28]:
july_2026 = pd.read_csv(csv_url)

In [29]:
page_url = "https://www.caa.co.uk/data-and-analysis/uk-aviation-market/airlines/uk-airline-data/uk-airline-data-2026/july-2026/"

page_response = requests.get(page_url)

page_response.status_code

200

In [30]:
"Table 03" in page_response.text

True

In [31]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(page_response.text, "html.parser")

In [32]:
for link in soup.find_all("a"):
    if "Table 03" in link.get_text():
        print(link.get_text(strip=True))
        print(link.get("href"))

Table 03 All Services (CSV, 3 KB)
/Documents/Download/26869/7bccbe92-007a-455b-a7ae-c206f9b1676d/4838
Table 03 All Services (PDF, 147 KB)
/Documents/Download/26869/7bccbe92-007a-455b-a7ae-c206f9b1676d/4840

In [33]:
for link in soup.find_all("a"):
    if "Table 03" in link.get_text() and "CSV" in link.get_text():
        csv_path = link.get("href")

csv_path

'/Documents/Download/26869/7bccbe92-007a-455b-a7ae-c206f9b1676d/4838'

In [34]:
full_csv_url = "https://www.caa.co.uk" + csv_path

full_csv_url

'https://www.caa.co.uk/Documents/Download/26869/7bccbe92-007a-455b-a7ae-c206f9b1676d/4838'

In [35]:
test_df = pd.read_csv(full_csv_url)

test_df.shape

(32, 15)

In [36]:
test_page_url = "https://www.caa.co.uk/data-and-analysis/uk-aviation-market/airlines/uk-airline-data/uk-airline-data-2026/june-2026/"

test_response = requests.get(test_page_url)

test_response.status_code

200

In [37]:
test_soup = BeautifulSoup(test_response.text, "html.parser")

for link in test_soup.find_all("a"):
    if "Table 03" in link.get_text() and "CSV" in link.get_text():
        print(link.get_text(strip=True))
        print(link.get("href"))

Table 03 All Services (CSV, 3 KB)
/Documents/Download/26870/c123b5d6-0b07-4b4f-bdf3-fa782aeb1082/4810

In [38]:
june_csv_path = None

for link in test_soup.find_all("a"):
    if "Table 03" in link.get_text() and "CSV" in link.get_text():
        june_csv_path = link.get("href")

june_csv_url = "https://www.caa.co.uk" + june_csv_path

june_csv_url

'https://www.caa.co.uk/Documents/Download/26870/c123b5d6-0b07-4b4f-bdf3-fa782aeb1082/4810'

In [39]:
june_csv_path = None

In [40]:
june_2026 = pd.read_csv(june_csv_url)

june_2026.shape

(32, 15)

In [41]:
def get_caa_table03(year, month):
    print(year)
    print(month)

In [42]:
get_caa_table03(2026, "june")

2026
june

In [43]:
def get_caa_table03(year, month):
    page_url = f"https://www.caa.co.uk/data-and-analysis/uk-aviation-market/airlines/uk-airline-data/uk-airline-data-{year}/{month}-{year}/"
    
    print(page_url)

In [44]:
get_caa_table03(2026, "june")

https://www.caa.co.uk/data-and-analysis/uk-aviation-market/airlines/uk-airline-data/uk-airline-data-2026/june-2026/

In [45]:
def get_caa_table03(year, month):
    page_url = f"https://www.caa.co.uk/data-and-analysis/uk-aviation-market/airlines/uk-airline-data/uk-airline-data-{year}/{month}-{year}/"

    response = requests.get(page_url)

    return response.status_code

In [46]:
get_caa_table03(2026, "june")

200

In [47]:
def get_caa_table03(year, month):
    page_url = f"https://www.caa.co.uk/data-and-analysis/uk-aviation-market/airlines/uk-airline-data/uk-airline-data-{year}/{month}-{year}/"

    response = requests.get(page_url)

    soup = BeautifulSoup(response.text, "html.parser")

    return soup

In [48]:
soup = BeautifulSoup(response.text, "html.parser")

In [49]:
def get_caa_table03(year, month):
    page_url = f"https://www.caa.co.uk/data-and-analysis/uk-aviation-market/airlines/uk-airline-data/uk-airline-data-{year}/{month}-{year}/"

    response = requests.get(page_url)

    soup = BeautifulSoup(response.text, "html.parser")

    for link in soup.find_all("a"):
        if "Table 03" in link.get_text() and "CSV" in link.get_text():
            csv_path = link.get("href")

    full_csv_url = "https://www.caa.co.uk" + csv_path

    df = pd.read_csv(full_csv_url)

    return df

In [50]:
june_test = get_caa_table03(2026, "june")

june_test.shape

(32, 15)

In [51]:
july_test = get_caa_table03(2026, "july")

july_test.shape

(32, 15)

In [52]:
jan_2019_test = get_caa_table03(2019, "january")

jan_2019_test.shape

(35, 15)

In [53]:
jan_2019_test["reporting_period"].unique()

array([201901])

In [54]:
months = pd.date_range(
    start="2019-01-01",
    end="2026-07-01",
    freq="MS"
)

len(months)

91

In [55]:
for date in months[:5]:
    print(date.year, date.strftime("%B").lower())

2019 january
2019 february
2019 march
2019 april
2019 may

In [56]:
test_datasets = []

for date in months[:3]:
    year = date.year
    month = date.strftime("%B").lower()

    df_month = get_caa_table03(year, month)

    test_datasets.append(df_month)

    print(year, month, df_month.shape)

2019 january (35, 15)
2019 february (34, 15)
2019 march (36, 15)

In [57]:
test_combined = pd.concat(test_datasets, ignore_index=True)

test_combined.shape

(105, 15)

In [58]:
all_datasets = []
failed_months = []

for date in months:
    year = date.year
    month = date.strftime("%B").lower()

    try:
        df_month = get_caa_table03(year, month)
        all_datasets.append(df_month)
        print(f"Success: {year} {month}")

    except Exception as error:
        failed_months.append((year, month, str(error)))
        print(f"Failed: {year} {month} - {error}")

Success: 2019 january
Success: 2019 february
Success: 2019 march
Success: 2019 april
Success: 2019 may
Success: 2019 june
Success: 2019 july
Success: 2019 august
Success: 2019 september
Success: 2019 october
Success: 2019 november
Success: 2019 december
Success: 2020 january
Success: 2020 february
Success: 2020 march
Success: 2020 april
Success: 2020 may
Success: 2020 june
Success: 2020 july
Success: 2020 august
Success: 2020 september
Success: 2020 october
Success: 2020 november
Success: 2020 december
Success: 2021 january
Success: 2021 february
Success: 2021 march
Success: 2021 april
Success: 2021 may
Success: 2021 june
Success: 2021 july
Success: 2021 august
Success: 2021 september
Success: 2021 october
Success: 2021 november
Success: 2021 december
Success: 2022 january
Success: 2022 february
Success: 2022 march
Success: 2022 april
Success: 2022 may
Success: 2022 june
Success: 2022 july
Success: 2022 august
Success: 2022 september
Success: 2022 october
Success: 2022 november
Success: 2022 december
Success: 2023 january
Success: 2023 february
Success: 2023 march
Success: 2023 april
Success: 2023 may
Success: 2023 june
Success: 2023 july
Success: 2023 august
Success: 2023 september
Success: 2023 october
Success: 2023 november
Success: 2023 december
Success: 2024 january
Success: 2024 february
Success: 2024 march
Success: 2024 april
Success: 2024 may
Success: 2024 june
Success: 2024 july
Success: 2024 august
Success: 2024 september
Success: 2024 october
Success: 2024 november
Success: 2024 december
Success: 2025 january
Success: 2025 february
Success: 2025 march
Success: 2025 april
Success: 2025 may
Success: 2025 june
Success: 2025 july
Success: 2025 august
Success: 2025 september
Success: 2025 october
Success: 2025 november
Success: 2025 december
Success: 2026 january
Success: 2026 february
Success: 2026 march
Success: 2026 april
Success: 2026 may
Success: 2026 june
Success: 2026 july

In [59]:
print("Successful months:", len(all_datasets))
print("Failed months:", len(failed_months))
print("Failed details:", failed_months)

Successful months: 91
Failed months: 0
Failed details: []

In [60]:
caa_historical = pd.concat(all_datasets, ignore_index=True)

caa_historical.shape

(3443, 15)

In [61]:
caa_historical.isna().sum()

rundate                                0
reporting_period                       0
type_of_operations                     0
airline_name                           0
aircraft_km_x1000                      0
no_flights                             0
aircraft_hours                         0
total_passengers_uplifted              0
seat_km_available_x1000                0
seat_km_used_x1000                     0
cargo_tonnes_uplifted                  0
total_tonne_km_available_x1000         0
tot_mail_tonne_km_used_x1000           0
total_freight_tonne_km_used_x1000      0
total_passenger_tonne_km_used_x1000    0
dtype: int64

In [62]:
caa_historical.duplicated().sum()

np.int64(0)

In [63]:
caa_historical["reporting_period"].nunique()

91

In [64]:
print("Earliest period:", caa_historical["reporting_period"].min())
print("Latest period:", caa_historical["reporting_period"].max())

Earliest period: 201901
Latest period: 202607

In [65]:
expected_periods = set(months.strftime("%Y%m"))

actual_periods = set(
    caa_historical["reporting_period"].astype(str)
)

missing_periods = expected_periods - actual_periods

print("Missing months:", sorted(missing_periods))

Missing months: []

In [66]:
duplicate_records = caa_historical.duplicated(
    subset=[
        "reporting_period",
        "airline_name",
        "type_of_operations"
    ]
)

print("Duplicate airline-period records:", duplicate_records.sum())

Duplicate airline-period records: 0

In [67]:
airlines = sorted(caa_historical["airline_name"].unique())

print("Number of unique airline names:", len(airlines))

for airline in airlines:
    print(airline)

Number of unique airline names: 45
2 EXCEL AVIATION LTD T/A THE BLADES BROADSWORD SCIMITAR SABRE AND T2
ACROPOLIS AVIATION LTD
AER LINGUS (UK) LTD
AIRTANKER SERVICES LTD
ASCEND AIRWAYS LTD
ASL AIRLINES UK LTD
AURIGNY AIR SERVICES
BA CITYFLYER LTD
BA EUROFLYER LTD DBA BRITISH AIRWAYS
BAE SYSTEMS (CORP AIR TVL) LTD
BLUE ISLANDS LIMITED
BRITISH AIRWAYS PLC
CARGOLOGICAIR LTD
CATREUS AOC LTD
CONCIERGE U LTD
DHL AIR LTD
EASTERN AIRWAYS
EASYJET UK LTD
EMERALD AIRLINES UK LTD
EUROPEAN CARGO LTD
EXECUJET EUROPE
EXECUTIVE JET CHARTER LTD
FLYBE LTD
GAMA AVIATION (UK) LTD
JET2.COM LTD
JOTA AVIATION LTD
LOGANAIR LTD
LONDON EXECUTIVE AVIATION LTD
MAERSK AIR CARGO UK LTD
NORSE ATLANTIC UK LTD
NORWEGIAN AIR UK LTD
ONE AIR LTD
PEN-AVIA LTD
RVL AVIATION LTD
RYANAIR UK LTD
SAXONAIR CHARTER LTD
TAG AVIATION (UK) LTD
THOMAS COOK AIRLINES LTD
TITAN AIRWAYS LTD
TUI AIRWAYS LTD
VIRGIN ATLANTIC AIRWAYS LTD
VIRGIN ATLANTIC INTERNATIONAL
VOLUXIS LTD
WEST ATLANTIC UK LTD
WIZZ AIR UK LTD

In [68]:
ba_airlines = caa_historical[
    caa_historical["airline_name"].isin([
        "BA CITYFLYER LTD",
        "BA EUROFLYER LTD DBA BRITISH AIRWAYS",
        "BRITISH AIRWAYS PLC"
    ])
]

ba_airlines.groupby(
    ["airline_name", "type_of_operations"]
).size()

airline_name                          type_of_operations
BA CITYFLYER LTD                      Passenger             91
BA EUROFLYER LTD DBA BRITISH AIRWAYS  Passenger             43
BRITISH AIRWAYS PLC                   Cargo                 91
                                      Passenger             91
dtype: int64

In [69]:
euroflyer = ba_airlines[
    ba_airlines["airline_name"] == "BA EUROFLYER LTD DBA BRITISH AIRWAYS"
]

print("First reporting period:", euroflyer["reporting_period"].min())
print("Last reporting period:", euroflyer["reporting_period"].max())

First reporting period: 202301
Last reporting period: 202607

In [70]:
caa_historical.to_csv(
    "data/interim/caa_table03_2019_2026_combined.csv",
    index=False
)

print("Historical CAA dataset saved successfully.")

Historical CAA dataset saved successfully.

In [71]:
caa_historical["type_of_operations"].value_counts()

type_of_operations
Passenger    2553
Cargo         890
Name: count, dtype: int64

In [72]:
caa_passenger = caa_historical[
    caa_historical["type_of_operations"] == "Passenger"
].copy()

print("Passenger dataset shape:", caa_passenger.shape)

Passenger dataset shape: (2553, 15)

In [73]:
caa_passenger.dtypes

rundate                                  str
reporting_period                       int64
type_of_operations                       str
airline_name                             str
aircraft_km_x1000                      int64
no_flights                             int64
aircraft_hours                         int64
total_passengers_uplifted              int64
seat_km_available_x1000                int64
seat_km_used_x1000                     int64
cargo_tonnes_uplifted                  int64
total_tonne_km_available_x1000         int64
tot_mail_tonne_km_used_x1000           int64
total_freight_tonne_km_used_x1000      int64
total_passenger_tonne_km_used_x1000    int64
dtype: object

In [74]:
columns_to_check = [
    "no_flights",
    "total_passengers_uplifted",
    "seat_km_available_x1000",
    "seat_km_used_x1000"
]

(caa_passenger[columns_to_check] < 0).sum()

no_flights                   0
total_passengers_uplifted    0
seat_km_available_x1000      0
seat_km_used_x1000           0
dtype: int64

In [75]:
(caa_passenger[columns_to_check] == 0).sum()

no_flights                     0
total_passengers_uplifted    129
seat_km_available_x1000        0
seat_km_used_x1000             1
dtype: int64

In [76]:
zero_passengers = caa_passenger[
    caa_passenger["total_passengers_uplifted"] == 0
]

zero_passengers.groupby("airline_name").size().sort_values(ascending=False)

airline_name
RVL AVIATION LTD                                                        85
RYANAIR UK LTD                                                          19
VOLUXIS LTD                                                             12
ASCEND AIRWAYS LTD                                                       9
BA EUROFLYER LTD DBA BRITISH AIRWAYS                                     2
2 EXCEL AVIATION LTD T/A THE BLADES BROADSWORD SCIMITAR SABRE AND T2     1
LONDON EXECUTIVE AVIATION LTD                                            1
dtype: int64

In [77]:
caa_passenger["load_factor_pct"] = (
    caa_passenger["seat_km_used_x1000"]
    / caa_passenger["seat_km_available_x1000"]
    * 100
)

print(
    "Records above 100%:",
    (caa_passenger["load_factor_pct"] > 100).sum()
)

print(
    "Maximum load factor:",
    caa_passenger["load_factor_pct"].max()
)

Records above 100%: 0
Maximum load factor: 100.0

In [78]:
caa_passenger["date"] = pd.to_datetime(
    caa_passenger["reporting_period"].astype(str),
    format="%Y%m"
)

caa_passenger[["reporting_period", "date"]].head()

   reporting_period       date
0            201901 2019-01-01
1            201901 2019-01-01
2            201901 2019-01-01
3            201901 2019-01-01
4            201901 2019-01-01

In [79]:
ba_cityflyer = caa_passenger[
    caa_passenger["airline_name"] == "BA CITYFLYER LTD"
].copy()

ba_cityflyer = ba_cityflyer.sort_values("date")

print("BA Cityflyer records:", len(ba_cityflyer))

ba_cityflyer[[
    "date",
    "no_flights",
    "total_passengers_uplifted",
    "load_factor_pct"
]].head()

BA Cityflyer records: 91

          date  no_flights  total_passengers_uplifted  load_factor_pct
4   2019-01-01        3059                     174199        62.914941
39  2019-02-01        3334                     204657        69.387305
73  2019-03-01        3683                     235098        71.770979
109 2019-04-01        3551                     226066        70.967609
145 2019-05-01        3922                     256239        72.744414

In [80]:
ba_cityflyer["passengers_per_flight"] = (
    ba_cityflyer["total_passengers_uplifted"]
    / ba_cityflyer["no_flights"]
)

ba_cityflyer["avg_flight_distance_km"] = (
    ba_cityflyer["aircraft_km_x1000"] * 1000
    / ba_cityflyer["no_flights"]
)

ba_cityflyer[[
    "date",
    "passengers_per_flight",
    "avg_flight_distance_km",
    "load_factor_pct"
]].head().round(2)

/var/folders/_n/f3jnwygx67zfvbm2_2x8jblw0000gn/T/ipykernel_32730/3771540281.py:16: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  ]].head().round(2)

          date  passengers_per_flight  avg_flight_distance_km  load_factor_pct
4   2019-01-01                  56.95                  662.63            62.91
39  2019-02-01                  61.38                  650.27            69.39
73  2019-03-01                  63.83                  664.40            71.77
109 2019-04-01                  63.66                  665.45            70.97
145 2019-05-01                  65.33                  712.65            72.74

In [81]:
ba_cityflyer[[
    "date",
    "passengers_per_flight",
    "avg_flight_distance_km",
    "load_factor_pct"
]].head().style.format({
    "passengers_per_flight": "{:.2f}",
    "avg_flight_distance_km": "{:.2f}",
    "load_factor_pct": "{:.2f}"
})

In [82]:
caa_passenger.to_csv(
    "data/processed/caa_passenger_2019_2026.csv",
    index=False
)

print("Passenger dataset saved successfully.")

Passenger dataset saved successfully.

In [83]:
ba_cityflyer.to_csv(
    "data/processed/ba_cityflyer_2019_2026.csv",
    index=False
)

print("BA Cityflyer dataset saved successfully.")

BA Cityflyer dataset saved successfully.